apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /exports-ocp4/
    server: 192.168.50.254
  persistentVolumeReclaimPolicy: Delete
  #  storageClassName: nfs-storage
  volumeMode: Filesystem
