apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /nfsdemo/
    server: 192.168.50.254
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
